criterion:
  type: BCEWithLogitsLoss
dataframe:
  mixup_thr: 200

  use_africa: false
  pseudo_2021_config:
    use: false
  pseudo_2021_xc_config:
    use: false
  pseudo_2022_config:
    use: false
  pseudo_2022_xc_config:
    use: false
  pseudo_2023_config:
    inference_type: window
    use: false
  pseudo_2023_xc_config:
    inference_type: window
    use: false
    
  train_2021_config:
    drop: false
    filter_threshold: 0
    max_duration: 60
    upsample_threshold: 20
    use: true
  train_2022_config:
    drop: false
    filter_threshold: 0
    max_duration: 360
    upsample_threshold: 20
    use: true
  train_2023_config:
    drop: false
    filter_threshold: 0
    max_duration: 360
    upsample_threshold: 20
    use: false
  weight_from_rating: true
  xc_2021_data_config:
    downsample_threshold: 9999
    max_duration: 999
    use: false
  xc_2022_data_config:
    downsample_threshold: 9999
    max_duration: 999
    use: false
  xc_2023_data_config:
    downsample_threshold: 9999
    max_duration: 999
    upsample_smallest_n: 0
    upsample_threshold: 0
    use: false
    full: false
  zendodo_config:
    max_duration: 5
    use: false
dataset:
  audio_mix_up_prob: 0.0
  fmax: 16000
  fmin: 20
  freq_mask_prob: 0.0
  hop_length: 512
  mel_norm: false
  n_mels: 128
  nfft: 2028
  noise_aug_prob: 0.2
  normalize: true
  sample_rate: 32000
  second_time_mask_prob: 0.0
  time_mask_prob: 0.0
  top_db: 80
  train_audio_len: 160000
  train_batch_size: 32
  train_duration: 5
  use_brown_noise: false
  use_esc50_noise: false
  use_gaussian_noise: true
  use_no_call_noise: false
  use_noise_injection: false
  use_pink_noise: false
  valid_audio_len: 160000
  valid_batch_size: 32
  valid_duration: 5
  window: 2048
environment:
  n_workers: 4
  seed: 42
experiment_name: exp164_pretrain_pretrain
fold: -1
logger:
  job_type: training
  project: birdclef-2023
  train_print_frequency: 100
  use_wandb: true
  valid_print_frequency: 100
model:
  finetune_head: false
  finetune_top_layers: false
  architecture: custom
  backbone_type: tf_efficientnet_b4_ns
  dropout: 0.5
  freeze_n_layers: 0
  hidden_dropout: 0.1
  reinitialize_n_layers: 1
optimizer:
  betas:
  - 0.9
  - 0.999
  decoder_lr: 0.0005
  embeddings_lr: 0.0005
  encoder_lr: 0.0005
  eps: 1.0e-06
  group_lr_multiplier: 1
  n_groups: 1
  weight_decay: 0.001
run_id: exp164_pretrain_pretrain_fold-1_3
run_name: exp164_pretrain_pretrain_fold-1
scheduler:
  constant_schedule_with_warmup:
    n_warmup_steps: 0
  cosine_schedule_with_warmup:
    n_cycles: 0.5
    n_warmup_steps: 0
  type: cosine_schedule_with_warmup
training:
  apex: false
  epochs: 20
  evaluate_n_times_per_epoch: 1
  max_grad_norm: 1
